version: "3.9"

services:
  backend:
    build: ./backend
    container_name: prolog-backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
      - /app/node_modules
    command: ["npm", "start"]
    environment:
      - NODE_ENV=development

  frontend:
    build: ./frontend
    container_name: prolog-frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: ["npm", "run", "dev", "--", "--host"]
    environment:
      - NODE_ENV=development
    depends_on:
      - backend
